---
title: "Findings"
format: html
---


```{r}
#| echo: false
#| warning: false
library(tidyverse)
```


```{r}
#| echo: false
white <- read.csv("whiteSummary.csv", header=TRUE)
black <- read.csv("blackSummary.csv", header=TRUE)
hispanic <- read.csv("hispanicSummary.csv", header=TRUE)
haw <- read.csv("hawSummary.csv", header=TRUE)
asian <- read.csv("asianSummary.csv", header=TRUE)
amIndian <- read.csv("amIndianSummary.csv",header=TRUE)
top3 <- read.csv("top3SummaryByRac.csv",header=TRUE)
pops <- read.csv("pops.csv", header=TRUE)
```


```{r}
#| echo: false

lung_white <- white %>% filter(!(diseaseSite %in% c("Breast", "Pancreas")))
lung_black <- black %>% filter(!(diseaseSite %in% c("Liver", "Prostate")))
lung_hispanic <- hispanic %>% filter(!(diseaseSite %in% c("Liver","Pancreas")))
lung_asian <- asian %>% filter(!(diseaseSite %in% c("Liver","Pancreas")))

pops_asian <- pops %>% filter(!(Race %in% c("black", "hispanic")))
pops_hispanic <- pops %>% filter(!(Race %in% c("black", "asian")))
pops_black <- pops %>% filter(!(Race %in% c("asian", "hispanic")))
```

```{r}
#| echo: false
library(ggplot2)

# Create a combined dataframe 
lung_df <- bind_rows(
  mutate(lung_white, Race = "White", Rate = deaths / pops_hispanic$Population * 100000),
  mutate(lung_black, Race = "Black", Rate = deaths / pops_black$Population * 100000),
  mutate(lung_hispanic, Race = "Hispanic", Rate = deaths / pops_hispanic$Population * 100000),
  mutate(lung_asian, Race = "Asian", Rate = deaths / pops_asian$Population * 100000)
)

ggplot(lung_df, aes(x = ddodyear, y = Rate, color = Race)) +
  geom_line(size = 1.2) +
  geom_point() +
  labs(title = "Lung Cancer Death Rate (per 100,000) by Race (2014–2023)",
       x = "Year", y = "Death Rate per 100,000") +
  theme_minimal() +
  scale_color_brewer(palette = "Set1")


```

```{r}
#| echo: false
#this is the first graph
plot(lung_hispanic$ddodyear, (lung_hispanic$deaths/pops_hispanic$Population)*100000, 
     frame = FALSE, pch = 19, col = "red", type="b", lty=2,
     main = "Lung Cancer 2014-2023 for Asian, Black, and Hispanic Populations",
     xlab = "Year", ylab = "Number of Deaths per 100,000", 
     ylim = c(0, 50))
lines(lung_asian$ddodyear, (lung_asian$deaths/pops_asian$Population)*100000, pch=18, col="blue", type="b", lty=2)
lines(lung_black$ddodyear, (lung_black$deaths/pops_black$Population)*100000, pch=22, col="green", type="b", lty=2)
```

```{r}
#| echo: false
#2nd 
cancer_types <- c("Lung", "Pancreas", "Breast")
death_rates <- c(28.25, 10.02, 8.79)
colors <- c("blue", "green", "red")

percent_labels <- paste0(round(death_rates / sum(death_rates) * 100, 1), "%")

pie(
  death_rates,
  labels = percent_labels,
  col = colors,
  main = "Top 3 Cancer Death Rates per 100,000\nWhite Population, 2014–2023"
)


legend(
  "topright",
  legend = cancer_types,
  fill = colors,
  title = "Cancer Type",
  cex = 0.9
)

```


```{r}
#| echo: false
#6th 
plot(lung_white$ddodyear, (lung_white$deaths/pops_hispanic$Population)*100000, 
     frame = FALSE, pch = 19, col = "red", type="b", lty=2,
     main = "Lung Cancer 2014-2023 for White Populations",
     xlab = "Year", ylab = "Number of Deaths per 100,000", 
     ylim = c(0, 350))
```

```{r}
#| echo: false
#3rd black
cancer_types <- c("Lung", "Liver", "Prostate")
death_rates <- c(28.00, 10.88, 10.88)
colors <- c("blue", "yellow", "red")

percent_labels <- paste0(round(death_rates / sum(death_rates) * 100, 1), "%")

pie(
  death_rates,
  labels = percent_labels,
  col = colors,
  main = "Top 3 Cancer Death Rates per 100,000\nBlack Population, 2014–2023"
)

legend("topright", legend = cancer_types, fill = colors, title = "Cancer Type", cex = 0.9)

```


```{r}
#| echo: false
#4th Hispanic
cancer_types <- c("Lung", "Pancreas", "Liver")
death_rates <- c(4.11, 2.38, 2.16)
colors <- c("blue", "green", "yellow")

percent_labels <- paste0(round(death_rates / sum(death_rates) * 100, 1), "%")

pie(
  death_rates,
  labels = percent_labels,
  col = colors,
  main = "Top 3 Cancer Death Rates per 100,000\nHispanic Population, 2014–2023"
)

legend("topright", legend = cancer_types, fill = colors, title = "Cancer Type", cex = 0.9)

```

```{r}
#| echo: false
#5th Asian
cancer_types <- c("Lung", "Liver", "Pancreas")
death_rates <- c(18.50, 8.47, 6.74)
colors <- c("blue", "yellow", "green")

percent_labels <- paste0(round(death_rates / sum(death_rates) * 100, 1), "%")

pie(
  death_rates,
  labels = percent_labels,
  col = colors,
  main = "Top 3 Cancer Death Rates per 100,000\nAsian Population, 2014–2023"
)

legend("topright", legend = cancer_types, fill = colors, title = "Cancer Type", cex = 0.9)
```
