---
title: "Methods"
format: html
---

This study analyzes cancer mortality data from Multnomah County over the past ten years. The original dataset, obtained in raw form, constrained over 80,000 entries representing all recorded deaths within the county during the study period. All dad processing and analysis were conducted in RStudio.

To prepare the data for analysis, we must thank Jeremy McWilliams for his help. Without his guidance and edits, this project would be incomplete. We first restricted the dataset to entries that had a recorded response for the race and ethnicity variable. We further filtered the dataset by identifying descendants whose cause of death was cancer-related. This identification was based on matching International Classification of Diseases, 10th Revision (ICD-10) codes associated with various types of cancer.  Following this filtering process, a substantial number of individual records remained for analysis, each representing a single cancer-related death.

To account for differences in population size across racial and ethnic groups, we calculated cancer mortality rates per 100,000 individuals. Population estimates were drawn from the U.S. Census Bureau’s American Community Survey (ACS) 5-year estimates for Multnomah County, with annual data collected corresponding to the years under study. The use of 5 year ACS estimates ensures greater statistical reliability, particularly for smaller racial and ethnic subgroups. 

The dataset thus used for this study consists of individual-level cancer mortality records aggregated over the ten-year period. Cause of death was determined by the attending physician and recorded on the death certificate. Race and ethnicity information was drawn from vital records; this information is typically self-reported by the individual during life or by family members, and may be subject to underreporting or misclassification.

Racial and ethnic classifications within the dataset follow the categories outlined by the REALD (Race, Ethnicity, Language, and Disability) data collection framework, which was the standard at the time of data collection. While future data systems such as REALD+ aim to provide more detailed granularity, the categories available for this study include:

-   American Indian or Alaskan Native, non-Hispanic
-   Asian, non-Hispanic
-   Black or African American, non-Hispanic
-   Hispanic or Latino (of any race)
-   Native Hawaiian or Pacific Islander, non-Hispanic
-   White, non-Hispanic
-   Two or more races, non-Hispanic

By focusing exclusively on these groups, the study maintains consistency with existing administrative record-keeping standards, while acknowledging potential limitations in the accuracy of specificity of racial and ethnic identification. 


